[versions]

ios-support = "none"

adaptive = "0.25.719-SNAPSHOT"
agp = "8.2.0"
android-compileSdk = "34"
android-minSdk = "26"
android-targetSdk = "34"
android-material = "1.12.0"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.0"
androidx-espresso-core = "3.5.1"
androidx-test-junit = "1.1.5"
brotli4j = "1.16.0"
coroutines = "1.8.1"
datetime = "0.4.0"
gradle-download-plugin = "5.5.0"
gradle-maven-publish = "0.29.0"
javamail = "1.6.2"
junit = "4.13.2"
junit-bom = "5.9.1"
kctfork = "0.8.0"
kotlin = "2.2.0"
kotlin-wrappers = "1.0.0-pre.760"
kotlinx-io = "0.5.3"
ktor = "2.3.11"
logback = "1.5.6"
plugin-publish = "1.1.0"
plugin-android = "7.3.0"
shadow = "8.1.1"
slf4j = "2.0.13"
subethamail = "3.1.7"

[libraries]

adaptive-core-core = { module = "fun.adaptive:core-core", version.ref = "adaptive" }
adaptive-core-ui = { module = "fun.adaptive:core-ui", version.ref = "adaptive" }

adaptive-grove-doc = { module = "fun.adaptive:grove-doc", version.ref = "adaptive" }
adaptive-grove-lib = { module = "fun.adaptive:grove-lib", version.ref = "adaptive" }
adaptive-grove-runtime = { module = "fun.adaptive:grove-runtime", version.ref = "adaptive" }

adaptive-lib-app = { module = "fun.adaptive:lib-app", version.ref = "adaptive" }
adaptive-lib-auth = { module = "fun.adaptive:lib-auth", version.ref = "adaptive" }
adaptive-lib-chart = { module = "fun.adaptive:lib-chart", version.ref = "adaptive" }
adaptive-lib-graphics = { module = "fun.adaptive:lib-graphics", version.ref = "adaptive" }
adaptive-lib-ktor = { module = "fun.adaptive:lib-ktor", version.ref = "adaptive" }
adaptive-lib-document = { module = "fun.adaptive:lib-document", version.ref = "adaptive" }
adaptive-lib-test = { module = "fun.adaptive:lib-test", version.ref = "adaptive" }
adaptive-lib-ui = { module = "fun.adaptive:lib-ui", version.ref = "adaptive" }
adaptive-lib-ui-mpw = { module = "fun.adaptive:lib-ui-mpw", version.ref = "adaptive" }
adaptive-lib-util = { module = "fun.adaptive:lib-util", version.ref = "adaptive" }
adaptive-lib-value = { module = "fun.adaptive:lib-value", version.ref = "adaptive" }

adaptive-site-lib-cookbook = { module = "fun.adaptive:site-lib-cookbook", version.ref = "adaptive" }

android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }

brotli4j = { module = "com.aayushatharva.brotli4j:brotli4j", version.ref = "brotli4j" }
brotli4j-linux = { module = "com.aayushatharva.brotli4j:native-linux-x86_64", version.ref = "brotli4j" }
brotli4j-linux-aarch64 = { module = "com.aayushatharva.brotli4j:native-linux-aarch64", version.ref = "brotli4j" }
brotli4j-macos = { module = "com.aayushatharva.brotli4j:native-osx-x86_64", version.ref = "brotli4j" }
brotli4j-macos-aarch64 = { module = "com.aayushatharva.brotli4j:native-osx-aarch64", version.ref = "brotli4j" }
brotli4j-windows = { module = "com.aayushatharva.brotli4j:native-windows-x86_64", version.ref = "brotli4j" }

javamail = { module = "com.sun.mail:javax.mail", version.ref = "javamail" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }

kctfork = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork"}

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
kotlin-compiler-internal-test-framework = { module = "org.jetbrains.kotlin:kotlin-compiler-internal-test-framework", version.ref = "kotlin" }
kotlin-script-runtime = { module = "org.jetbrains.kotlin:kotlin-script-runtime", version.ref = "kotlin" }
kotlin-annotations-jvm = { module = "org.jetbrains.kotlin:kotlin-annotations-jvm", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

kotlin-wrappers-web = { module = "org.jetbrains.kotlin-wrappers:kotlin-web", version.ref = "kotlin-wrappers" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug", version.ref = "coroutines" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-forwardedheaders = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-android-api = { module = "com.android.tools.build:gradle-api", version.ref = "plugin-android" }

slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }

subethamail = { module = "org.subethamail:subethasmtp", version.ref = "subethamail" }

[plugins]

adaptive = { id = "fun.adaptive", version.ref = "adaptive" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
download = { id = "de.undercouch.download", version.ref = "gradle-download-plugin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
gradleMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish" }